tasks:
  - name: Setup MongoDB
    init: |
      sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
      echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/4.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.4.list
      sudo apt-get update
      sudo apt-get install -y mongodb-org
      sudo mkdir -p /data/db
      sudo chown -R gitpod:gitpod /data/db
      sudo mkdir -p /var/log/mongodb
      sudo chown -R gitpod:gitpod /var/log/mongodb
      mongod --bind_ip 127.0.0.1 --dbpath=/data/db --fork --logpath=/var/log/mongodb/mongod.log
  - name: Start Server
    command: npm run dev