version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: wizfi
      MONGO_INITDB_ROOT_PASSWORD: Wisdomwise1
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data:
